import type { DashboardData } from './types';

export const MOCK_DASHBOARD_DATA: DashboardData = {
  lastUpdated: new Date().toISOString(),

  kpis: [
    {
      id: 'revenue',
      label: 'Revenue (MTD)',
      value: '£284,500',
      previousValue: '£251,200',
      change: 13.2,
      trend: 'up',
      description: 'vs last month',
    },
    {
      id: 'deals',
      label: 'Deals Closed',
      value: 47,
      previousValue: 39,
      change: 20.5,
      trend: 'up',
      description: 'vs last month',
    },
    {
      id: 'pipeline',
      label: 'Pipeline Value',
      value: '£1.2M',
      previousValue: '£980K',
      change: 22.4,
      trend: 'up',
      description: 'open opportunities',
    },
    {
      id: 'win_rate',
      label: 'Win Rate',
      value: '34%',
      previousValue: '31%',
      change: 3,
      trend: 'up',
      description: 'last 90 days',
    },
    {
      id: 'avg_deal',
      label: 'Avg Deal Size',
      value: '£6,053',
      previousValue: '£6,441',
      change: -6.0,
      trend: 'down',
      description: 'vs last month',
    },
    {
      id: 'clients',
      label: 'Active Clients',
      value: 138,
      previousValue: 131,
      change: 5.3,
      trend: 'up',
      description: 'total accounts',
    },
  ],

  revenueChart: [
    { month: 'Jan', revenue: 198000, target: 220000, deals: 31 },
    { month: 'Feb', revenue: 215000, target: 220000, deals: 34 },
    { month: 'Mar', revenue: 241000, target: 230000, deals: 38 },
    { month: 'Apr', revenue: 228000, target: 240000, deals: 35 },
    { month: 'May', revenue: 251200, target: 250000, deals: 39 },
    { month: 'Jun', revenue: 284500, target: 260000, deals: 47 },
  ],

  pipeline: [
    { id: 'prospect',    name: 'Prospect',       value: 380000, count: 24, color: '#6B7280', percentage: 100 },
    { id: 'qualified',   name: 'Qualified',      value: 290000, count: 16, color: '#2563EB', percentage: 76 },
    { id: 'proposal',    name: 'Proposal',        value: 210000, count: 11, color: '#7C3AED', percentage: 55 },
    { id: 'negotiation', name: 'Negotiation',    value: 185000, count: 8,  color: '#C8693B', percentage: 49 },
    { id: 'closed',      name: 'Closed Won',     value: 284500, count: 47, color: '#1C4532', percentage: 75 },
  ],

  recentActivity: [
    {
      id: 'a1',
      type: 'deal_won',
      title: 'Deal closed',
      description: 'Meridian Group — Enterprise licence',
      user: { name: 'Sarah Chen', initials: 'SC', color: '#1C4532' },
      timestamp: '2026-06-27T09:14:00Z',
      relativeTime: '12 min ago',
      meta: '£42,000',
    },
    {
      id: 'a2',
      type: 'client_added',
      title: 'New client added',
      description: 'Thornfield Logistics onboarded',
      user: { name: 'Marcus Webb', initials: 'MW', color: '#2563EB' },
      timestamp: '2026-06-27T08:51:00Z',
      relativeTime: '35 min ago',
    },
    {
      id: 'a3',
      type: 'meeting_scheduled',
      title: 'Meeting scheduled',
      description: 'Demo call with Vantage Capital',
      user: { name: 'Priya Nair', initials: 'PN', color: '#7C3AED' },
      timestamp: '2026-06-27T08:20:00Z',
      relativeTime: '1 hr ago',
      meta: 'Mon 2 Jul, 14:00',
    },
    {
      id: 'a4',
      type: 'invoice_sent',
      title: 'Invoice sent',
      description: 'INV-2847 to Albion Partners',
      user: { name: 'Tom Ridley', initials: 'TR', color: '#C8693B' },
      timestamp: '2026-06-27T07:45:00Z',
      relativeTime: '2 hr ago',
      meta: '£8,750',
    },
    {
      id: 'a5',
      type: 'deal_lost',
      title: 'Deal marked lost',
      description: 'Apex Solutions — budget freeze',
      user: { name: 'Sarah Chen', initials: 'SC', color: '#1C4532' },
      timestamp: '2026-06-26T16:30:00Z',
      relativeTime: 'Yesterday',
      meta: '£19,000',
    },
    {
      id: 'a6',
      type: 'task_completed',
      title: 'Task completed',
      description: 'Q2 pipeline review deck',
      user: { name: 'Marcus Webb', initials: 'MW', color: '#2563EB' },
      timestamp: '2026-06-26T15:10:00Z',
      relativeTime: 'Yesterday',
    },
  ],

  topClients: [
    { id: 'c1', name: 'Meridian Group',       industry: 'Finance',       revenue: 128000, deals: 4, status: 'active',   initials: 'MG', color: '#1C4532' },
    { id: 'c2', name: 'Albion Partners',      industry: 'Consulting',    revenue: 96500,  deals: 6, status: 'active',   initials: 'AP', color: '#2563EB' },
    { id: 'c3', name: 'Vantage Capital',      industry: 'Investment',    revenue: 84000,  deals: 3, status: 'active',   initials: 'VC', color: '#7C3AED' },
    { id: 'c4', name: 'Thornfield Logistics', industry: 'Logistics',     revenue: 61200,  deals: 5, status: 'active',   initials: 'TL', color: '#C8693B' },
    { id: 'c5', name: 'Apex Solutions',       industry: 'Technology',    revenue: 52000,  deals: 2, status: 'at_risk',  initials: 'AS', color: '#6B7280' },
  ],

  teamPerformance: [
    { id: 't1', name: 'Sarah Chen',   role: 'Senior AE',   initials: 'SC', color: '#1C4532', deals: 18, revenue: 112000, target: 100000, winRate: 42 },
    { id: 't2', name: 'Marcus Webb',  role: 'Account Exec', initials: 'MW', color: '#2563EB', deals: 14, revenue: 89500,  target: 90000,  winRate: 38 },
    { id: 't3', name: 'Priya Nair',   role: 'Account Exec', initials: 'PN', color: '#7C3AED', deals: 9,  revenue: 57000,  target: 80000,  winRate: 29 },
    { id: 't4', name: 'Tom Ridley',   role: 'Junior AE',   initials: 'TR', color: '#C8693B', deals: 6,  revenue: 26000,  target: 50000,  winRate: 24 },
  ],

  upcomingTasks: [
    { id: 'tk1', title: 'Send proposal',         client: 'Vantage Capital',      due: 'Today, 17:00',   priority: 'high',   type: 'proposal'  },
    { id: 'tk2', title: 'Follow-up call',        client: 'Apex Solutions',       due: 'Today, 15:30',   priority: 'high',   type: 'call'      },
    { id: 'tk3', title: 'Product demo',          client: 'Norwood Media',        due: 'Mon 30 Jun',     priority: 'medium', type: 'demo'      },
    { id: 'tk4', title: 'Contract review',       client: 'Albion Partners',      due: 'Tue 1 Jul',      priority: 'medium', type: 'meeting'   },
    { id: 'tk5', title: 'Quarterly check-in',   client: 'Thornfield Logistics', due: 'Wed 2 Jul',      priority: 'low',    type: 'meeting'   },
  ],
};
